 ### 列表

#### 列表概述

In [1]:
a = [1,2,3]#列表
a

[1, 2, 3]

In [2]:
type(a)#查看类型

list

In [3]:
a[0]#列表从0开始索引

1

#### 列表的操作

In [4]:
a.append(4)#追加元素至列表末尾
a

[1, 2, 3, 4]

In [5]:
a.insert(2,'a')#就是在列表第三位插入'a'
a

[1, 2, 'a', 3, 4]

In [6]:
a.remove('a')  #按名称移除列表中第一个指定元素
a

[1, 2, 3, 4]

In [7]:
del a[3]  #移除指定位置上的元素
a

[1, 2, 3]

In [8]:
b = [4,5,6]
a.extend(b)  #将列表b合并到a后面
a

[1, 2, 3, 4, 5, 6]

In [9]:
a.pop(2)  #移除指定位置元素，并返回该元素的值

3

In [10]:
a.reverse()  #将列表顺序颠倒
a

[6, 5, 4, 2, 1]

In [11]:
a.sort()  #按从小到大顺序排列
a

[1, 2, 4, 5, 6]

In [12]:
a.count(3)  #计算列表中指定元素的个数

0

In [13]:
a.index(2)  #求列表中该元素第一次出现的的索引

1

In [14]:
a.pop()  #移除list中的最后一个元素，并且返回该元素的值。

6

#### 列表值传递和地址传递

In [15]:
c1 = a
c2 = a[:]
c3 = a.copy()
c1,c2,c3

([1, 2, 4, 5], [1, 2, 4, 5], [1, 2, 4, 5])

In [16]:
a.append(6)
[c1,c2,c3] #只有c1是和a同步变化，为地址传递

[[1, 2, 4, 5, 6], [1, 2, 4, 5], [1, 2, 4, 5]]

##### 列表的嵌套

In [17]:
m = [[1, 2, 3, 4],[5, 6, 7, 8, 9],[ 10, 11, 12]]
type(m)

list

In [18]:
print(m)#列表时不要用规规整整的

[[1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12]]


In [19]:
m[1][2]#查找第2个列表的第三个值

7

##### 生成列表的方式

In [20]:
list(range(1,10,2))#第一种，使用range等距生成，range的第一个数字是几就是几，不要-1

[1, 3, 5, 7, 9]

In [21]:
[x for x in range(1, 11)]#way2，使用函数生成

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
[m + n for m in 'ABC' for n in 'XYZ']#也可以以字符串为元素，这两个for相当于嵌套

['AX', 'AY', 'AZ', 'BX', 'BY', 'BZ', 'CX', 'CY', 'CZ']

### 集合

In [23]:
a = {1,2,2,'a','a','bc'}  #集合中元素不重复，重复的会自动删除
a

{1, 2, 'a', 'bc'}

In [24]:
type(a)

set

In [25]:
'a' in a  #用in判断是否在a中，返回true 或 false

True

In [26]:
b = {1,3,'b','c'}
a | b#求集合的并集

{1, 2, 3, 'a', 'b', 'bc', 'c'}

In [27]:
a & b  #求集合的交

{1}

In [28]:
a - b  #求集合的差，a-b表示在a中，不在b中的元素的集合

{2, 'a', 'bc'}

In [29]:
a ^ b   #求两集合的异或，a^b=(a | b)-(a & b)

{2, 3, 'a', 'b', 'bc', 'c'}

In [30]:
set('122abb')#就是单独拆开

{'1', '2', 'a', 'b'}

### 元组

In [31]:
a = 1,'a','b'   #元组由逗号分隔的多个值组成
a

(1, 'a', 'b')

In [32]:
type(a)

tuple

In [33]:
b = [1,'stacey']
c = a,b  #元组中可以嵌套不同类型的数据
c

((1, 'a', 'b'), [1, 'stacey'])

In [34]:
c[0]

(1, 'a', 'b')

In [35]:
c[0][1]

'a'

In [36]:
c[0] = 1#元组是不可变的，但是它们可以包含可变对象。

TypeError: 'tuple' object does not support item assignment

In [37]:
c[1][1]=2
c

((1, 'a', 'b'), [1, 2])

### 字典

In [38]:
tel = {'Stacey':520, 'Mary':462, 'Joey':639}
print(tel)
type(tel)

{'Stacey': 520, 'Mary': 462, 'Joey': 639}


dict

In [39]:
tel = dict(Stacey= 520, Mary = 462, Joey = 639)
tel

{'Stacey': 520, 'Mary': 462, 'Joey': 639}

In [40]:
tel = dict([('Stacey',520),('Mary',462),('Joey',639)]) #将一个由关键字与值构成的元组对序列变成字典
tel

{'Stacey': 520, 'Mary': 462, 'Joey': 639}

In [41]:
print(tel.keys())
print(tel.values())  #分别访问关键字与值

dict_keys(['Stacey', 'Mary', 'Joey'])
dict_values([520, 462, 639])


In [42]:
list(tel.keys())#输出关键词

['Stacey', 'Mary', 'Joey']

In [43]:
sorted(tel.keys())  #排序

['Joey', 'Mary', 'Stacey']

In [44]:
tel['Stacey']

520

In [45]:
'Mike' in tel

False

In [46]:
tel['Honey'] = 880  #添加元素
tel

{'Stacey': 520, 'Mary': 462, 'Joey': 639, 'Honey': 880}

In [47]:
tel['Honey'] = 890  #修改值
tel

{'Stacey': 520, 'Mary': 462, 'Joey': 639, 'Honey': 890}

In [48]:
del tel['Joey']  #删除指定元素
tel

{'Stacey': 520, 'Mary': 462, 'Honey': 890}

### 倒入模块

#### math模块（提供浮点数数学运算）

In [49]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

##### way1

In [50]:
import math
math.exp(1)

2.718281828459045

##### way2

In [51]:
import math as mt
mt.exp(1)

2.718281828459045

##### way3

In [52]:
from math import exp 
exp(1) 

2.718281828459045

##### way4

In [53]:
from math import exp as myexp 
myexp(1)

2.718281828459045

#### numpy

In [54]:
import numpy as np
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

##### 求矩阵转置

In [55]:
A.T

array([[1, 3],
       [2, 4]])

#### scipy

In [56]:
from scipy import linalg
B = linalg.inv(A) # 求矩阵的逆
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### 矩阵乘法

In [57]:
A.dot(B) 

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

#### matplotlib(2D绘图库）

In [58]:
import matplotlib.pyplot as plt

x = [1,2,3,4,5,6]
y = [3,4,6,2,4,8]

plt.plot(x, y)

### 函数

#### 汉诺塔

In [59]:
def move(n, a, b, c):
    if n == 1:
            print(a, '-->', c)
    else:
        move(n-1, a, c, b)
        move(1, a, b, c)
        move(n-1, b, a, c)

In [60]:
move(3, 'A', 'B', 'C')

A --> C
A --> B
C --> B
A --> C
B --> A
B --> C
A --> C


### 生成器

In [61]:
def triangles(n):    #杨辉三角
    L = [1]
    for x in range(n):
        yield L
        L = [1] + [L[i] + L[i+1] for i in range(len(L)-1)] + [1]

In [62]:
for x in triangles(10):   #通过for循环来迭代它
    print(x)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
[1, 7, 21, 35, 35, 21, 7, 1]
[1, 8, 28, 56, 70, 56, 28, 8, 1]
[1, 9, 36, 84, 126, 126, 84, 36, 9, 1]


### 高阶函数

In [63]:
def minus(x, y, f):
    return f(x) - f(y)

In [64]:
minus(1, 0, exp)

1.718281828459045

In [65]:
list(map(str, [1, 2, 3, 4, 5, 6, 7, 8, 9])) #将传入的函数依次作用到序列的每个元素，并把结果返回。

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [66]:
def normalize(name):  #将名字中的字母大小写规范化
    name = name.lower()
    name = name.capitalize()
    return name

In [67]:
L = ['StaceY', 'LISA', 'joey']
list(map(normalize, L))

['Stacey', 'Lisa', 'Joey']

In [68]:
list(filter(lambda x: x % 2 == 1, [1, 2, 4, 5, 6, 9, 10, 15]))  #返回list中的奇数

[1, 5, 9, 15]

In [69]:
sorted([30, 5, -12, 9, -21], key=abs) #按照keys中函数作用后的结果进行排序，并按照对应关系返回list相应的元素 

[5, 9, -12, -21, 30]

### csv文件处理

In [70]:
import csv

data = {'name':['stacey','lily','joey'], 'date':[2017,2018,2017], 'grade' : [100,99,98]}
with open('grades.csv', 'w') as f:
    wr = csv.writer(f, delimiter=' ')
        wr.writerow(data['name'])
        wr.writerow(data['date'])
        wr.writerow(data['grade'])

IndentationError: unexpected indent (<ipython-input-70-3022ee81d5e7>, line 6)

In [71]:
import csv
data = {'name':['stacey','lily','joey'], 'date':[2017,2018,2017], 'grade' : [100,99,98]}
with open('grades.csv','w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=' ')
    writer.writerow(data['name'])
    writer.writerow(data['date'])
    writer.writerow(data['grade'])

In [72]:
data['grade']

[100, 99, 98]

In [73]:
import pandas  
data2 = pandas.read_csv('grades.csv') 
data2

stacey lily joey
0   2017 2018 2017
1        100 99 98

### 文本处理

In [74]:
import nltk

In [75]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/stacey_ckk/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [76]:
para = "Stacey is a adorable girl and she is so addited to music. This is the reason why she is listening to music while she is doing this tds task. "

In [77]:
from nltk.tokenize import sent_tokenize 
sent_tokenize(para)#分成句子

['Stacey is a adorable girl and she is so addited to music.',
 'This is the reason why she is listening to music while she is doing this tds task.']

In [78]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/stacey_ckk/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

#### 去除stopwords

In [79]:
from nltk.tokenize import word_tokenize
word_tokenize(para)#分成词

['Stacey',
 'is',
 'a',
 'adorable',
 'girl',
 'and',
 'she',
 'is',
 'so',
 'addited',
 'to',
 'music',
 '.',
 'This',
 'is',
 'the',
 'reason',
 'why',
 'she',
 'is',
 'listening',
 'to',
 'music',
 'while',
 'she',
 'is',
 'doing',
 'this',
 'tds',
 'task',
 '.']

In [80]:
from nltk.corpus import stopwords
english_stops = set(stopwords.words('english'))
print(english_stops)  #输出stopwords

{'her', 'should', 'my', 'while', 'the', 'y', "shan't", 'themselves', 'ma', 'aren', 'own', 'it', 'through', 'why', 'we', 'ourselves', 'had', "you'll", 'yourself', 'than', 'such', 'when', 'for', 'o', 'at', "that'll", 'here', 'you', 'how', 'because', "you'd", 'being', 'doing', 'in', 'with', 've', 'again', 're', 'shan', 'myself', 'his', "haven't", "isn't", 'isn', 'or', 'during', 'no', 'above', 'until', 'which', 'is', 'do', "weren't", "it's", 'to', 'just', 'couldn', "you're", 'now', "aren't", 'hasn', 'yours', 'on', 'don', 'yourselves', 'doesn', 'will', 's', 'have', 'but', 'any', 'himself', 'further', 'very', 'their', 'both', 'them', 'by', 't', 'below', 'whom', 'into', 'am', 'where', 'me', 'd', "should've", 'other', "hasn't", 'nor', 'under', 'hers', 'i', 'him', 'are', 'some', 'didn', 'been', 'can', 'more', 'those', 'against', 'an', "shouldn't", 'did', 'before', 'needn', 'all', 'off', "don't", 'mustn', 'these', 'between', 'ain', 'up', "won't", 'ours', 'same', "hadn't", "wouldn't", 'has', 'be'

In [81]:
from nltk.tokenize import RegexpTokenizer 
tokenizer = RegexpTokenizer("[\w']+") 
words = tokenizer.tokenize("Listening to music is a bad habit while working.") 
words

['Listening', 'to', 'music', 'is', 'a', 'bad', 'habit', 'while', 'working']

In [82]:
[word for word in words if word not in english_stops]#去除stopwords

['Listening', 'music', 'bad', 'habit', 'working']

#### 去除词缀

In [83]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmer.stem('loving')

'love'

In [84]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmer.stem('loved')

'love'