### 打开文件

In [1]:
with open("data/BABAnews.txt", mode = 'r') as myfile: 
        print(myfile.read())
        myfile.closed# 特别注意要记得关闭！！！

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



#### 更好的习惯：先读取如变量中，立刻关闭。

In [2]:
myfile = open("data/BABAnews.txt", mode = 'r')
text = myfile.read()
myfile.close()
print(text)

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



### 读取全部文件

In [3]:
myfile = open("data/BABAnews.txt", mode = 'r')
myfile.read()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n'

### 读取文件的一句话

In [4]:
myfile = open("data/BABAnews.txt", mode = 'r')
myfile.readline()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n'

In [5]:
myfile.readline()#再输入一遍就继续读取

'    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n'

In [6]:
myfile.readlines()# 将剩余的话全部读取

['    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n',
 '    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n',
 '    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n']

### 读取csv

In [7]:
with open('data/Titanic.csv', 'r') as myfile:
    for line in myfile:
        print(line, end ='')

ID,Class,Sex,Age,Survived,Freq
1,1st,Male,Child,No,0
2,2nd,Male,Child,No,0
3,3rd,Male,Child,No,35
4,Crew,Male,Child,No,0
5,1st,Female,Child,No,0
6,2nd,Female,Child,No,0
7,3rd,Female,Child,No,17
8,Crew,Female,Child,No,0
9,1st,Male,Adult,No,118
10,2nd,Male,Adult,No,154
11,3rd,Male,Adult,No,387
12,Crew,Male,Adult,No,670
13,1st,Female,Adult,No,4
14,2nd,Female,Adult,No,13
15,3rd,Female,Adult,No,89
16,Crew,Female,Adult,No,3
17,1st,Male,Child,Yes,5
18,2nd,Male,Child,Yes,11
19,3rd,Male,Child,Yes,13
20,Crew,Male,Child,Yes,0
21,1st,Female,Child,Yes,1
22,2nd,Female,Child,Yes,13
23,3rd,Female,Child,Yes,14
24,Crew,Female,Child,Yes,0
25,1st,Male,Adult,Yes,57
26,2nd,Male,Adult,Yes,14
27,3rd,Male,Adult,Yes,75
28,Crew,Male,Adult,Yes,192
29,1st,Female,Adult,Yes,140
30,2nd,Female,Adult,Yes,80
31,3rd,Female,Adult,Yes,76
32,Crew,Female,Adult,Yes,20

### 写文件

In [8]:
file = open('data/testfile.txt', 'w') 
file.write('Hello World \n') 
file.write('and this is another line.') 
file.close() 

In [9]:
buy = ['milk\n', 'butter\n', 'coffee beans\n', 'arugula\n']
file = open('data/grocerylist.txt', 'w')
file.writelines(buy) # writelines(list)
file.close()

#### 不能写入浮点数，必须转化为str字符

In [10]:
pi = 3.141592
fout = open('data/math.txt', 'w')
fout.write("Pi's value is ")
fout.write(str(pi))
fout.close()

### 读取txt文件

 #### way1

In [11]:
import numpy as np 
data = np.loadtxt('data/BJsales.txt', skiprows = 1, delimiter='\t')
print(data)

[[  1.    1.  200.1]
 [  2.    2.  199.5]
 [  3.    3.  199.4]
 [  4.    4.  198.9]
 [  5.    5.  199. ]
 [  6.    6.  200.2]
 [  7.    7.  198.6]
 [  8.    8.  200. ]
 [  9.    9.  200.3]
 [ 10.   10.  201.2]
 [ 11.   11.  201.6]
 [ 12.   12.  201.5]
 [ 13.   13.  201.5]
 [ 14.   14.  203.5]
 [ 15.   15.  204.9]
 [ 16.   16.  207.1]
 [ 17.   17.  210.5]
 [ 18.   18.  210.5]
 [ 19.   19.  209.8]
 [ 20.   20.  208.8]
 [ 21.   21.  209.5]
 [ 22.   22.  213.2]
 [ 23.   23.  213.7]
 [ 24.   24.  215.1]
 [ 25.   25.  218.7]
 [ 26.   26.  219.8]
 [ 27.   27.  220.5]
 [ 28.   28.  223.8]
 [ 29.   29.  222.8]
 [ 30.   30.  223.8]
 [ 31.   31.  221.7]
 [ 32.   32.  222.3]
 [ 33.   33.  220.8]
 [ 34.   34.  219.4]
 [ 35.   35.  220.1]
 [ 36.   36.  220.6]
 [ 37.   37.  218.9]
 [ 38.   38.  217.8]
 [ 39.   39.  217.7]
 [ 40.   40.  215. ]]


 #### way2

In [12]:
import csv
with open('data/Titanic.csv') as csvfile:
    titanicReader = csv.reader(csvfile)
    for row in titanicReader:
        print('  '.join(row))

ID  Class  Sex  Age  Survived  Freq
1  1st  Male  Child  No  0
2  2nd  Male  Child  No  0
3  3rd  Male  Child  No  35
4  Crew  Male  Child  No  0
5  1st  Female  Child  No  0
6  2nd  Female  Child  No  0
7  3rd  Female  Child  No  17
8  Crew  Female  Child  No  0
9  1st  Male  Adult  No  118
10  2nd  Male  Adult  No  154
11  3rd  Male  Adult  No  387
12  Crew  Male  Adult  No  670
13  1st  Female  Adult  No  4
14  2nd  Female  Adult  No  13
15  3rd  Female  Adult  No  89
16  Crew  Female  Adult  No  3
17  1st  Male  Child  Yes  5
18  2nd  Male  Child  Yes  11
19  3rd  Male  Child  Yes  13
20  Crew  Male  Child  Yes  0
21  1st  Female  Child  Yes  1
22  2nd  Female  Child  Yes  13
23  3rd  Female  Child  Yes  14
24  Crew  Female  Child  Yes  0
25  1st  Male  Adult  Yes  57
26  2nd  Male  Adult  Yes  14
27  3rd  Male  Adult  Yes  75
28  Crew  Male  Adult  Yes  192
29  1st  Female  Adult  Yes  140
30  2nd  Female  Adult  Yes  80
31  3rd  Female  Adult  Yes  76
32  Crew  Female  Adult  Yes

 #### way3

In [13]:
import pandas as pd
titanicData = pd.read_csv('data/Titanic.csv') 
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

#### way4

In [14]:
titanicData = pd.read_table('data/Titanic.csv', sep=',')
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

#### way5

In [15]:
sales = pd.read_csv('data/BJsales.csv', header = None)
sales.head()

0  1      2
0  1  1  200.1
1  2  2  199.5
2  3  3  199.4
3  4  4  198.9
4  5  5  199.0

#### way6

In [16]:
sales = pd.read_csv('data/BJsales.csv', names=['ID', 'Time', 'Value'])
sales.head()

ID  Time  Value
0   1     1  200.1
1   2     2  199.5
2   3     3  199.4
3   4     4  198.9
4   5     5  199.0

### 将数据保存成csv

In [17]:
sales.to_csv('data/sales.csv', index = True)

### 读取excel

In [18]:
import pandas as pd
file = 'data/example.xlsx'
myfile = pd.ExcelFile(file) 
print(myfile.sheet_names) #printing out all the sheet names in the excel file
dataframe = myfile.parse('HairEyeColor') #extracting data from the first sheet as a dataframe
dataframe.head()

['HairEyeColor', 'Nile']


ID   Hair    Eye   Sex  Freq
0   1  Black  Brown  Male    32
1   2  Brown  Brown  Male    53
2   3    Red  Brown  Male    10
3   4  Blond  Brown  Male     3
4   5  Black   Blue  Male    11