In [1]:
with open("data/a.txt",encoding="utf-8",mode="r") as myfile:
    print(myfile.read())

111
222
333


In [2]:
with open("data/a.txt",encoding="utf-8",mode="r") as myfile:
    print(myfile.readline())

111



In [3]:
with open("data/a.txt",encoding="utf-8",mode="r") as myfile:
    print(myfile.readlines())

['111\n', '222\n', '333']


In [6]:
myfile.closed

True

在文件比较大的时候可以用以下循环方式，节省内存

In [7]:
with open("data/Titanic.csv","r") as myfile:
    for l in myfile:
        print(l,end="")

ID,Class,Sex,Age,Survived,Freq
1,1st,Male,Child,No,0
2,2nd,Male,Child,No,0
3,3rd,Male,Child,No,35
4,Crew,Male,Child,No,0
5,1st,Female,Child,No,0
6,2nd,Female,Child,No,0
7,3rd,Female,Child,No,17
8,Crew,Female,Child,No,0
9,1st,Male,Adult,No,118
10,2nd,Male,Adult,No,154
11,3rd,Male,Adult,No,387
12,Crew,Male,Adult,No,670
13,1st,Female,Adult,No,4
14,2nd,Female,Adult,No,13
15,3rd,Female,Adult,No,89
16,Crew,Female,Adult,No,3
17,1st,Male,Child,Yes,5
18,2nd,Male,Child,Yes,11
19,3rd,Male,Child,Yes,13
20,Crew,Male,Child,Yes,0
21,1st,Female,Child,Yes,1
22,2nd,Female,Child,Yes,13
23,3rd,Female,Child,Yes,14
24,Crew,Female,Child,Yes,0
25,1st,Male,Adult,Yes,57
26,2nd,Male,Adult,Yes,14
27,3rd,Male,Adult,Yes,75
28,Crew,Male,Adult,Yes,192
29,1st,Female,Adult,Yes,140
30,2nd,Female,Adult,Yes,80
31,3rd,Female,Adult,Yes,76
32,Crew,Female,Adult,Yes,20

.write()只能写单个string，.writelines()可以写只含strings的list.写入的如果是non-string type要先用str()转化

In [9]:
file=open("data/testfile.txt","w")
file.write("Hello world\n")
file.write("another line.")
file.close()

In [10]:
file=open("data/testfile.txt","r")
text=file.read()
print(text)
file.close()

Hello world
another line.


In [11]:
tobuy=['a\n','b\n','c\n']
file=open("data/grocerylist.txt","w")
file.writelines(tobuy)#writelines()可以写只含strings的list
file.close()

In [15]:
pi=3.141592
file=open("data/math.txt","w")
file.write("pi's value is "+str(pi))
file.close()
file=open("data/math.txt","r")
text=file.read()
print(text)
file.close()

pi's value is 3.141592


用**numpy**读取txt文件

In [16]:
import numpy as np
data=np.loadtxt("data/BJsales.txt",skiprows=2,delimiter="\t")
print(data)

[[  2.    2.  199.5]
 [  3.    3.  199.4]
 [  4.    4.  198.9]
 [  5.    5.  199. ]
 [  6.    6.  200.2]
 [  7.    7.  198.6]
 [  8.    8.  200. ]
 [  9.    9.  200.3]
 [ 10.   10.  201.2]
 [ 11.   11.  201.6]
 [ 12.   12.  201.5]
 [ 13.   13.  201.5]
 [ 14.   14.  203.5]
 [ 15.   15.  204.9]
 [ 16.   16.  207.1]
 [ 17.   17.  210.5]
 [ 18.   18.  210.5]
 [ 19.   19.  209.8]
 [ 20.   20.  208.8]
 [ 21.   21.  209.5]
 [ 22.   22.  213.2]
 [ 23.   23.  213.7]
 [ 24.   24.  215.1]
 [ 25.   25.  218.7]
 [ 26.   26.  219.8]
 [ 27.   27.  220.5]
 [ 28.   28.  223.8]
 [ 29.   29.  222.8]
 [ 30.   30.  223.8]
 [ 31.   31.  221.7]
 [ 32.   32.  222.3]
 [ 33.   33.  220.8]
 [ 34.   34.  219.4]
 [ 35.   35.  220.1]
 [ 36.   36.  220.6]
 [ 37.   37.  218.9]
 [ 38.   38.  217.8]
 [ 39.   39.  217.7]
 [ 40.   40.  215. ]]


用**csv**和**pandas**读取csv文件

**csv.reader(file)**

In [20]:
import csv
with open('data/Titanic.csv') as file:
    reader=csv.reader(file)
    for rows in reader:
        print("\t".join(rows))# "". join()连接字符串数组。将字符串、元组、列表中的元素以指定的字符(""中的分隔符)连接生成一个新的字符串

ID	Class	Sex	Age	Survived	Freq
1	1st	Male	Child	No	0
2	2nd	Male	Child	No	0
3	3rd	Male	Child	No	35
4	Crew	Male	Child	No	0
5	1st	Female	Child	No	0
6	2nd	Female	Child	No	0
7	3rd	Female	Child	No	17
8	Crew	Female	Child	No	0
9	1st	Male	Adult	No	118
10	2nd	Male	Adult	No	154
11	3rd	Male	Adult	No	387
12	Crew	Male	Adult	No	670
13	1st	Female	Adult	No	4
14	2nd	Female	Adult	No	13
15	3rd	Female	Adult	No	89
16	Crew	Female	Adult	No	3
17	1st	Male	Child	Yes	5
18	2nd	Male	Child	Yes	11
19	3rd	Male	Child	Yes	13
20	Crew	Male	Child	Yes	0
21	1st	Female	Child	Yes	1
22	2nd	Female	Child	Yes	13
23	3rd	Female	Child	Yes	14
24	Crew	Female	Child	Yes	0
25	1st	Male	Adult	Yes	57
26	2nd	Male	Adult	Yes	14
27	3rd	Male	Adult	Yes	75
28	Crew	Male	Adult	Yes	192
29	1st	Female	Adult	Yes	140
30	2nd	Female	Adult	Yes	80
31	3rd	Female	Adult	Yes	76
32	Crew	Female	Adult	Yes	20


**pandas.read_csv()**

functions also includes 

read_excel,read_stata,read_json,read_html,read_sas......

In [21]:
import pandas as pd
td=pd.read_csv('data/Titanic.csv')
td.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

**pandas.read_table()** 需写明分隔符

In [22]:
td=pd.read_table('data/Titanic.csv',sep=",")
td.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

如果没有header

In [23]:
sales=pd.read_csv('data/BJsales.csv',header=None)
sales.head()

0  1      2
0  1  1  200.1
1  2  2  199.5
2  3  3  199.4
3  4  4  198.9
4  5  5  199.0

In [24]:
sales=pd.read_csv('data/BJsales.csv',names=["id",'time','value'])
sales.head()

id  time  value
0   1     1  200.1
1   2     2  199.5
2   3     3  199.4
3   4     4  198.9
4   5     5  199.0

Reading **Excle** file using **pandas**

In [27]:
file="data/example.xlsx"
myfile=pd.ExcelFile(file)
print(myfile.sheet_names)
dataframe=myfile.parse("HairEyeColor")#把HairEyeColor这个sheet中元素提取成一个dataframe
dataframe.head()

['HairEyeColor', 'Nile']


ID   Hair    Eye   Sex  Freq
0   1  Black  Brown  Male    32
1   2  Brown  Brown  Male    53
2   3    Red  Brown  Male    10
3   4  Blond  Brown  Male     3
4   5  Black   Blue  Male    11

Reading **pdf** file using **PyPDF2**

In [33]:
pip install PyPDF2

  Using cached PyPDF2-1.26.0.tar.gz (77 kB)
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61087 sha256=56af7a06394f0ed756f04b9089c63a7d4c030678395e109ae5afd9cd6f9d39c1
  Stored in directory: c:\users\der\appdata\local\pip\cache\wheels\80\1a\24\648467ade3a77ed20f35cfd2badd32134e96dd25ca811e64b3
Successfully built PyPDF2
Note: you may need to restart the kernel to use updated packages.


In [6]:
import PyPDF2
file=open('data/midasr.pdf','rb')
reader=PyPDF2.PdfFileReader(file)
reader.numPages
pageobj=reader.getPage(0)
print(pageobj.extractText())
file.close()

MixedFrequencyDataSamplingRegression
Models:the
RPackage
midasr
EricGhysels
UniversityofNorthCarolina
VirmantasKvedaras
VilniusUniversity
VaidotasZemlys
VilniusUniversity
Abstract
Regressionmodelsinvolvingdatasampledatdi
!
erentfrequenciesareofgeneralin-
terest.Inthisdocumentthe
Rpackage
midasr
isdescribedwithinaMIDASregression
frameworkwithfunctionalconstraintsonparametersputforwardinworkby
Ghysels,
Santa-Clara,andValkanov
(2002),Ghysels,Santa-Clara,andValkanov
(2006a)and
An-
dreou,Ghysels,andKourtellos
(2010).Keywords
:MIDAS,speciÞcationtest.
1.Introduction
Regressionmodelsinvolvingdatasampledatdi
!
erentfrequenciesareofgeneralinterest.In
thisdocumentweintroducea
Rpackage
midasr
fortheregressionmodelingwiththemixed
frequencydatabasedonaframeworkputforwardinrecentworkby
Ghysels
etal.
(2002),Ghysels
etal.
(2006a)and
Andreou
etal.
(2010)usingsocalledMIDAS,meaningMi(xed)
Da(ta)S(ampling),regressions.
1Inageneralframeworkofregressionswithfunctionalconstraintsonparameters,the
midasr
packag