In [13]:
from scipy import linalg
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [14]:
A=np.array([[1,2],[3,4]])

In [15]:
la,v=linalg.eig(A)

In [16]:
print(la)

[-0.37228132+0.j  5.37228132+0.j]


In [17]:
print(v)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [18]:
print(v[:1])

[[-0.82456484 -0.41597356]]


## scipy.stats
***

In [19]:
from scipy import stats

**getting help**

In [20]:
print(stats.norm.__doc__)

A normal continuous random variable.

    The location (``loc``) keyword specifies the mean.
    The scale (``scale``) keyword specifies the standard deviation.

    As an instance of the `rv_continuous` class, `norm` object inherits from it
    a collection of generic methods (see below for the full list),
    and completes them with details specific for this particular distribution.
    
    Methods
    -------
    rvs(loc=0, scale=1, size=1, random_state=None)
        Random variates.
    pdf(x, loc=0, scale=1)
        Probability density function.
    logpdf(x, loc=0, scale=1)
        Log of the probability density function.
    cdf(x, loc=0, scale=1)
        Cumulative distribution function.
    logcdf(x, loc=0, scale=1)
        Log of the cumulative distribution function.
    sf(x, loc=0, scale=1)
        Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
    logsf(x, loc=0, scale=1)
        Log of the survival function.
    ppf(q, loc=0, scale

The main public methods for continuous RVs are:

rvs: Random Variates

pdf: Probability Density Function

cdf: Cumulative Distribution Function

sf: Survival Function (1-CDF)

ppf: Percent Point Function (Inverse of CDF)

isf: Inverse Survival Function (Inverse of SF)

stats: Return mean, variance, (Fisher’s) skew, or (Fisher’s) kurtosis

moment: non-central moments of the distribution

To generate a sequence of random variates, use the size keyword argument:

In [24]:
stats.norm.rvs(size=[3,4])

array([[ 1.5126628 , -0.9670585 ,  0.5718266 , -1.23793021],
       [ 1.18240088,  1.42364858, -0.99514463, -0.92744733],
       [-0.1733263 , -0.45319856, -0.15728165, -0.11642538]])

In [28]:
np.info(stats.norm)

A normal continuous random variable.

The location (``loc``) keyword specifies the mean.
The scale (``scale``) keyword specifies the standard deviation.

As an instance of the `rv_continuous` class, `norm` object inherits from it
a collection of generic methods (see below for the full list),
and completes them with details specific for this particular distribution.

Methods
-------
rvs(loc=0, scale=1, size=1, random_state=None)
    Random variates.
pdf(x, loc=0, scale=1)
    Probability density function.
logpdf(x, loc=0, scale=1)
    Log of the probability density function.
cdf(x, loc=0, scale=1)
    Cumulative distribution function.
logcdf(x, loc=0, scale=1)
    Log of the cumulative distribution function.
sf(x, loc=0, scale=1)
    Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
logsf(x, loc=0, scale=1)
    Log of the survival function.
ppf(q, loc=0, scale=1)
    Percent point function (inverse of ``cdf`` --- percentiles).
isf(q, loc=0, scale=1)


In [29]:
from pandas. import datareader

ModuleNotFoundError: No module named 'pandas_datareader'