In [39]:
# Generate random numbers
# sudo pip3 install numpy
import numpy as np
dt0 = np.random.rand(100000)
dt0

array([0.2485198 , 0.93421088, 0.86285297, ..., 0.18748492, 0.89013192,
       0.00735607])

In [40]:
import time
t0 = time.perf_counter()
t0

7304.590424704

In [41]:
np.mean(dt0)

0.5009782578047827

In [42]:
t1 = time.perf_counter()
t1

7304.973162692

In [43]:
t = t1 - t0
t

0.38273798800037184

In [44]:
# Divide the data into 10 parts
dt1 = dt0.reshape(10, -1)
dt1

array([[0.2485198 , 0.93421088, 0.86285297, ..., 0.689004  , 0.41705636,
        0.12952297],
       [0.1954476 , 0.76290239, 0.38592307, ..., 0.05149107, 0.29443052,
        0.54641389],
       [0.65561575, 0.40813295, 0.25538025, ..., 0.5720512 , 0.12245225,
        0.42643927],
       ...,
       [0.78107663, 0.38932537, 0.86003837, ..., 0.95303572, 0.03893578,
        0.39893431],
       [0.91711082, 0.35019732, 0.61124395, ..., 0.76804808, 0.58829742,
        0.02030701],
       [0.62999806, 0.81679477, 0.30181765, ..., 0.18748492, 0.89013192,
        0.00735607]])

In [45]:
# Convert data to matrix form
mt = np.mat(dt1)
mt

matrix([[0.2485198 , 0.93421088, 0.86285297, ..., 0.689004  , 0.41705636,
         0.12952297],
        [0.1954476 , 0.76290239, 0.38592307, ..., 0.05149107, 0.29443052,
         0.54641389],
        [0.65561575, 0.40813295, 0.25538025, ..., 0.5720512 , 0.12245225,
         0.42643927],
        ...,
        [0.78107663, 0.38932537, 0.86003837, ..., 0.95303572, 0.03893578,
         0.39893431],
        [0.91711082, 0.35019732, 0.61124395, ..., 0.76804808, 0.58829742,
         0.02030701],
        [0.62999806, 0.81679477, 0.30181765, ..., 0.18748492, 0.89013192,
         0.00735607]])

In [46]:
t0 = time.perf_counter()
t0

7305.633904656

In [47]:
np.mean(np.mean(mt, 1))

0.5009782578047828

In [48]:
t1 = time.perf_counter()
t1

7305.942184228

In [49]:
t = t1 - t0
t

0.3082795720001741

In [50]:
# Value: 0.5009782578047828 = 0.5009782578047828

In [51]:
# Time(s): 0.3082795720001741 < 0.38273798800037184

In [ ]:
# The degree of discrimination is not obvious

In [ ]:
# Set a loop

In [180]:
t = np.array([])
for i in range(10000):
    t0 = time.perf_counter()
    np.mean(dt0)
    t1 = time.perf_counter()
    t = np.append(t, t1 - t0)
np.mean(t)

9.676780027803033e-05

In [181]:
t = np.array([])
for i in range(10000):
    t0 = time.perf_counter()
    np.mean(np.mean(mt, 1))
    t1 = time.perf_counter()
    t = np.append(t, t1 - t0)
np.mean(t)

8.619813929544762e-05