In [18]:
with open("BABAnews.txt",mode= 'r',encoding="UTF-8") as myfile:
    print(myfile.read())
   

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



In [21]:
myfile.closed

True

In [22]:
pwd

'C:\\Users\\Asus\\Desktop\\data'

In [24]:
myfile=open("BABAnews.txt",mode="r",encoding="UTF-8")
text = myfile.read()
myfile.close()
print(text)

    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。
    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。
    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。
    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”
    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）



In [25]:
myfile.read()#can be read after the file being closed

ValueError: I/O operation on closed file.

In [34]:
myfile=open("BABAnews.txt",mode='r',encoding='UTF-8')
myfile.read()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n\n'

In [40]:
myfile.read()
myfile.close()

In [41]:
myfile=open("BABAnews.txt",mode='r',encoding='UTF-8')
myfile.readline()

'    从2009年淘宝商城的促销活动，到2016年天猫商城全天交易额超越1207亿，“双十一”经过八年的升温，已经逐渐成长能够影响世界的中国电子商务行业年度盛事。在风光的“双十一”背后，技术保障团队又有什么样鲜为人知的故事呢？4月12日，阿里巴巴技术团队在京召开了分享会，独家揭秘“双十一”背后的“故事”，同时向大家推荐了题为《尽在双11——阿里巴巴技术演进与超越》的互联网丛书。\n'

In [42]:
myfile.readlines()

['    作为迄今为止，阿里巴巴集团唯一官方出品、全面阐述双 11 八年以来在技术和商业上演进和创新历程的书籍，《尽在双11——阿里巴巴技术演进与超越》由电子工业出版社博文视点与阿里巴巴联合出版。本书从五个方面全面精炼生动地进行剖析，揭秘世界奇迹双11背后的技术演进与创新，内容涵盖了双 11 背景下阿里技术架构八年来的演进，如何确保稳定性这条双 11 生命线的安全和可靠，技术和商业交织发展的历程，无线和互动的持续创新与突破，以及对商家的赋能和生态的促进与繁荣。\n',
 '    “1秒钟同时完成12万笔支付、单日交易额定格在1207亿元、每秒同时创建17.5万笔订单……”在这一串惊人的数字背后，蕴藏着技术团队鲜为人知的故事，对于他们来说，每年双11最紧张的就是午夜零点难以想象的流量。会议现场，双十一技术团部大队长陈琴、双十一稳定性负责人丁宇、认知计算实验室负责人袁泉分别从各自负责的业务板块，向大家细致解读了“双十一”背后，技术团队所付出的艰辛。三位负责人纷纷表示，他们分享的内容都包含在《尽在双11——阿里巴巴技术演进与超越》一书中，是双11八年成长经验与技术创新的总结，也是阿里成长中摸索出的方法和方向的汇聚，更是诸多技术同学与技术大神的倾囊分享。\n',
 '    阿里巴巴集团CEO张勇，对该书给予了高度的肯定。他认为，“《尽在双11——阿里巴巴技术演进与超越》以双11为着眼点，从技术的角度，展示了阿里巴巴的演进、变革与发展，系统地阐述了阿里巴巴重要阶段的技术进步历程。进无止境，我们希望将我们的经验分享给更多人，并希望与大家一起共同探索未来。”\n',
 '    阿里巴巴集团CTO张剑锋也力荐《尽在双11——阿里巴巴技术演进与超越》一书。他说，“《尽在双11——阿里巴巴技术演进与超越》是对“双11”技术演进客观、翔实的还原，迄今为止还没有类似的其他书。”（周靖杰）\n',
 '\n']

In [50]:
with open('Titanic.csv','r') as myfile:
    for line in myfile:
        print(line,end='')

ID,Class,Sex,Age,Survived,Freq
1,1st,Male,Child,No,0
2,2nd,Male,Child,No,0
3,3rd,Male,Child,No,35
4,Crew,Male,Child,No,0
5,1st,Female,Child,No,0
6,2nd,Female,Child,No,0
7,3rd,Female,Child,No,17
8,Crew,Female,Child,No,0
9,1st,Male,Adult,No,118
10,2nd,Male,Adult,No,154
11,3rd,Male,Adult,No,387
12,Crew,Male,Adult,No,670
13,1st,Female,Adult,No,4
14,2nd,Female,Adult,No,13
15,3rd,Female,Adult,No,89
16,Crew,Female,Adult,No,3
17,1st,Male,Child,Yes,5
18,2nd,Male,Child,Yes,11
19,3rd,Male,Child,Yes,13
20,Crew,Male,Child,Yes,0
21,1st,Female,Child,Yes,1
22,2nd,Female,Child,Yes,13
23,3rd,Female,Child,Yes,14
24,Crew,Female,Child,Yes,0
25,1st,Male,Adult,Yes,57
26,2nd,Male,Adult,Yes,14
27,3rd,Male,Adult,Yes,75
28,Crew,Male,Adult,Yes,192
29,1st,Female,Adult,Yes,140
30,2nd,Female,Adult,Yes,80
31,3rd,Female,Adult,Yes,76
32,Crew,Female,Adult,Yes,20

In [53]:
file= open('testfile.txt','w')
file.write('Hello World \n;')
file.write('and this is another line.')
file.close()

In [ ]:
This time, we have `tobuy`, a list of strings, which `writelines()` writes out at once:

In [56]:
tobuy = ['milk\n','butter\n','coffee beans\n','arugula\n']
file=open('grocerylist.txt','w')
file.writelines(tobuy)  # writelines(list)
file.close()

In [57]:
pi=3.141592
fout=open('math.txt','w')
fout.write("Pi's values is")
fout.write(pi) # trying to write float ,doesn't work

TypeError: write() argument must be str, not float

Only the string type can be written.

In [58]:
fout.write(str(pi))
fout.close()

> __Other ways to read text files__


> -We can also use other modules to read text files. For example, we can use numpy to read txt file. csv and pandas can be used to read csv files.

In [60]:
import numpy as np
data= np.loadtxt('BJsales.txt',skiprows=1,delimiter='\t')
print(data)

[[  1.    1.  200.1]
 [  2.    2.  199.5]
 [  3.    3.  199.4]
 [  4.    4.  198.9]
 [  5.    5.  199. ]
 [  6.    6.  200.2]
 [  7.    7.  198.6]
 [  8.    8.  200. ]
 [  9.    9.  200.3]
 [ 10.   10.  201.2]
 [ 11.   11.  201.6]
 [ 12.   12.  201.5]
 [ 13.   13.  201.5]
 [ 14.   14.  203.5]
 [ 15.   15.  204.9]
 [ 16.   16.  207.1]
 [ 17.   17.  210.5]
 [ 18.   18.  210.5]
 [ 19.   19.  209.8]
 [ 20.   20.  208.8]
 [ 21.   21.  209.5]
 [ 22.   22.  213.2]
 [ 23.   23.  213.7]
 [ 24.   24.  215.1]
 [ 25.   25.  218.7]
 [ 26.   26.  219.8]
 [ 27.   27.  220.5]
 [ 28.   28.  223.8]
 [ 29.   29.  222.8]
 [ 30.   30.  223.8]
 [ 31.   31.  221.7]
 [ 32.   32.  222.3]
 [ 33.   33.  220.8]
 [ 34.   34.  219.4]
 [ 35.   35.  220.1]
 [ 36.   36.  220.6]
 [ 37.   37.  218.9]
 [ 38.   38.  217.8]
 [ 39.   39.  217.7]
 [ 40.   40.  215. ]]


In [63]:
import csv
with open('Titanic.csv') as csvfile:
    titanicReader = csv.reader(csvfile)
    for row in titanicReader:
        print('   '.join(row))

ID   Class   Sex   Age   Survived   Freq
1   1st   Male   Child   No   0
2   2nd   Male   Child   No   0
3   3rd   Male   Child   No   35
4   Crew   Male   Child   No   0
5   1st   Female   Child   No   0
6   2nd   Female   Child   No   0
7   3rd   Female   Child   No   17
8   Crew   Female   Child   No   0
9   1st   Male   Adult   No   118
10   2nd   Male   Adult   No   154
11   3rd   Male   Adult   No   387
12   Crew   Male   Adult   No   670
13   1st   Female   Adult   No   4
14   2nd   Female   Adult   No   13
15   3rd   Female   Adult   No   89
16   Crew   Female   Adult   No   3
17   1st   Male   Child   Yes   5
18   2nd   Male   Child   Yes   11
19   3rd   Male   Child   Yes   13
20   Crew   Male   Child   Yes   0
21   1st   Female   Child   Yes   1
22   2nd   Female   Child   Yes   13
23   3rd   Female   Child   Yes   14
24   Crew   Female   Child   Yes   0
25   1st   Male   Adult   Yes   57
26   2nd   Male   Adult   Yes   14
27   3rd   Male   Adult   Yes   75
28   Crew   Male 

The `pandas` I/O API is a set of top level `reader` functions accessed like `read_csv()` that generally return a pandas object. These functions includes

    read_excel
    read_hdf
    read_sql
    read_json
    read_msgpack (experimental)
    read_html
    read_gbq (experimental)
    read_stata
    read_sas
    read_clipboard
    read_pickle
    
See [pandas IO tools](http://pandas.pydata.org/pandas-docs/stable/io.html) for detailed explanation.

__need some time to finish__

In [64]:
import pandas as pd
titanicData = pd.read_csv('Titanic.csv')
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

In [66]:
titanicData = pd.read_table('Titanic.csv',sep=',')
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

In [67]:
sales= pd.read_csv('BJsales.csv',header= None)
sales.head()

0  1      2
0  1  1  200.1
1  2  2  199.5
2  3  3  199.4
3  4  4  198.9
4  5  5  199.0

__names后面加的是列名__

In [70]:
sales= pd.read_csv('BJsales.csv',names=['ID','Time','Value'])
sales.head()

ID  Time  Value
0   1     1  200.1
1   2     2  199.5
2   3     3  199.4
3   4     4  198.9
4   5     5  199.0

In [71]:
sales.to_csv('salec.csv',index=False)

## Reading a Microsoft Excel file using `pandas`
Excel files are a huge part of any business operation and it becomes imperative that you learn exactly how to import these into python for data analysis. In order to do this we can use the code snippet shown below:

In [7]:
import pandas as pd
file ='data/example.xlsx'
myfile=pd.ExcelFile(file)
print(myfile.sheet_names) # printing out all the sheet names in the excel file
dataframe= myfile.parse('HairEyeColor') # extracting data from the first sheet as a dataframe
dataframe.head()

['HairEyeColor', 'Nile']


ID   Hair    Eye   Sex  Freq
0   1  Black  Brown  Male    32
1   2  Brown  Brown  Male    53
2   3    Red  Brown  Male    10
3   4  Blond  Brown  Male     3
4   5  Black   Blue  Male    11

## Reading a pdf file using `PyPDF2`

`PyPDF2` is a python library built as a PDF toolkit. It is capable of:

- Extracting document information (title, author, …)
- Splitting documents page by page
- Merging documents page by page
- Cropping pages
- Merging multiple pages into a single page
- Encrypting and decrypting PDF files
- and more!

Here we only demonstrate how to read a pdf file. Please find more details on https://pypi.org/project/PyPDF2/.

### need some time to master it !!!!!!!!!!!!!!!!!!!!

In [5]:
import PyPDF2
pdfFileObj = open('data/Li2011Wiley.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
pdfReader.numPages
pageObj = pdfReader.getPage(0)
print(pageObj.extractText())
pdfFileObj.close()

MODELINGCONDITIONALDENSITIESUSINGFINITESMOOTH
MIXTURES
FENGLI,MATTIASVILLANI,ANDROBERTKOHN
SverigesRiksbankWorkingPaperSeriesNo.245
August2010
Abstract.
Smoothmixtures,i.e.mixturemodelswithcovariate-depen
dentmixingweights,
areveryusefulexiblemodelsforconditionaldensities.P
reviousworkshowsthatusingtoo
simplemixturecomponentsformodelingheteroscedastican
d/orheavytaileddatacangive
apoort,evenwithalargenumberofcomponents.Thispapere
xploreshowwellasmooth
mixtureofsymmetriccomponentscancaptureskeweddata.Si
mulationsandapplicationson
realdatashowthatincludingcovariate-dependentskewnes
sinthecomponentscanleadto
substantiallyimprovedperformanceonskeweddata,oftenu
singamuchsmallernumberof
components.Furthermore,variableselectioniseectivei
nremovingunnecessarycovariatesin
theskewness,whichmeansthatthereislittlelossinallowi
ngforskewnessinthecomponents
whenthedataareactuallysymmetric.Wealsointroducesmoo
thmixturesofgammaand
log-normalcomponentstomodelpositively-valuedrespons
evariables.
Keywords

## Reading a word file using    `docx`

In [ ]:
i