In [1]:
pwd

'C:\\Users\\147\\Desktop\\2020\\DS tools\\Python\\py2'

In [22]:
file=open('data/testfile.txt','w')

In [23]:
file.write("hello,world!\n")

13

In [24]:
file.write("And this is another world.")

26

In [5]:
file.close()

In [25]:
tobuy = ['milk\n', 'butter\n', 'coffee beans\n', 'arugula\n','147\n']

In [26]:
file=open('data/grocerylist.txt','w')

In [27]:
file.writelines(tobuy)#writelines(list)

In [28]:
file.close()

In [18]:
file=open('data/grocerylist.txt','r')

In [19]:
file.read()

''

In [21]:
file.close()

In [29]:
pi=3.141592
fout = open('data/math.txt','w')
fout.write("Pi's value is ")
fout.write(pi)

TypeError: write() argument must be str, not float

In [30]:
fout.write(str(pi))

8

In [31]:
fout.close()

In [32]:
import numpy as np

In [34]:
data=np.loadtxt('data/BJsales.txt',skiprows = 1,delimiter='\t')
print(data)

[[   1.     1.   200.1]
 [   2.     2.   199.5]
 [   3.     3.   199.4]
 [   4.     4.   198.9]
 [   5.     5.   199. ]
 [   6.     6.   200.2]
 [   7.     7.   198.6]
 [   8.     8.   200. ]
 [   9.     9.   200.3]
 [  10.    10.   201.2]
 [  11.    11.   201.6]
 [  12.    12.   201.5]
 [  13.    13.   201.5]
 [  14.    14.   203.5]
 [  15.    15.   204.9]
 [  16.    16.   207.1]
 [  17.    17.   210.5]
 [  18.    18.   210.5]
 [  19.    19.   209.8]
 [  20.    20.   208.8]
 [  21.    21.   209.5]
 [  22.    22.   213.2]
 [  23.    23.   213.7]
 [  24.    24.   215.1]
 [  25.    25.   218.7]
 [  26.    26.   219.8]
 [  27.    27.   220.5]
 [  28.    28.   223.8]
 [  29.    29.   222.8]
 [  30.    30.   223.8]
 [  31.    31.   221.7]
 [  32.    32.   222.3]
 [  33.    33.   220.8]
 [  34.    34.   219.4]
 [  35.    35.   220.1]
 [  36.    36.   220.6]
 [  37.    37.   218.9]
 [  38.    38.   217.8]
 [  39.    39.   217.7]
 [  40.    40.   215. ]]


In [37]:
import csv
with open('data/Titanic.csv') as csvfile:
    titanicReader = csv.reader(csvfile)
    for row in titanicReader:
        print('   '.join(row))

ID   Class   Sex   Age   Survived   Freq
1   1st   Male   Child   No   0
2   2nd   Male   Child   No   0
3   3rd   Male   Child   No   35
4   Crew   Male   Child   No   0
5   1st   Female   Child   No   0
6   2nd   Female   Child   No   0
7   3rd   Female   Child   No   17
8   Crew   Female   Child   No   0
9   1st   Male   Adult   No   118
10   2nd   Male   Adult   No   154
11   3rd   Male   Adult   No   387
12   Crew   Male   Adult   No   670
13   1st   Female   Adult   No   4
14   2nd   Female   Adult   No   13
15   3rd   Female   Adult   No   89
16   Crew   Female   Adult   No   3
17   1st   Male   Child   Yes   5
18   2nd   Male   Child   Yes   11
19   3rd   Male   Child   Yes   13
20   Crew   Male   Child   Yes   0
21   1st   Female   Child   Yes   1
22   2nd   Female   Child   Yes   13
23   3rd   Female   Child   Yes   14
24   Crew   Female   Child   Yes   0
25   1st   Male   Adult   Yes   57
26   2nd   Male   Adult   Yes   14
27   3rd   Male   Adult   Yes   75
28   Crew   Male 

In [38]:
import pandas as pd
titanicData = pd.read_csv('data/Titanic.csv')
titanicData.head()

ID Class     Sex    Age Survived  Freq
0   1   1st    Male  Child       No     0
1   2   2nd    Male  Child       No     0
2   3   3rd    Male  Child       No    35
3   4  Crew    Male  Child       No     0
4   5   1st  Female  Child       No     0

In [40]:
sales = pd.read_csv('data/BJsales.csv', names=['I','LOVE','YOU'])
sales.head()

I  LOVE    YOU
0  1     1  200.1
1  2     2  199.5
2  3     3  199.4
3  4     4  198.9
4  5     5  199.0

In [41]:
import pandas as pd
file = 'data/example.xlsx'
myfile = pd.ExcelFile(file)

In [43]:
print(myfile.sheet_names)

['HairEyeColor', 'Nile']


In [44]:
dataframe=myfile.parse('HairEyeColor')
dataframe.head()

ID   Hair    Eye   Sex  Freq
0   1  Black  Brown  Male    32
1   2  Brown  Brown  Male    53
2   3    Red  Brown  Male    10
3   4  Blond  Brown  Male     3
4   5  Black   Blue  Male    11

In [47]:
import PyPDF2

In [46]:
pip install PyPDF2


The following command must be run outside of the IPython shell:

    $ pip install PyPDF2

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more informations on how to install packages:

    https://docs.python.org/3/installing/


In [48]:
pdfFileObj = open('data/Li2011Wiley.pdf','rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

In [49]:
pdfReader.numPages

1

In [50]:
pageObj = pdfReader.getPage(0)

In [51]:
print(pageObj.extractText())

MODELINGCONDITIONALDENSITIESUSINGFINITESMOOTH
MIXTURES
FENGLI,MATTIASVILLANI,ANDROBERTKOHN
SverigesRiksbankWorkingPaperSeriesNo.245
August2010
Abstract.
Smoothmixtures,i.e.mixturemodelswithcovariate-depen
dentmixingweights,
areveryusefulexiblemodelsforconditionaldensities.P
reviousworkshowsthatusingtoo
simplemixturecomponentsformodelingheteroscedastican
d/orheavytaileddatacangive
apoort,evenwithalargenumberofcomponents.Thispapere
xploreshowwellasmooth
mixtureofsymmetriccomponentscancaptureskeweddata.Si
mulationsandapplicationson
realdatashowthatincludingcovariate-dependentskewnes
sinthecomponentscanleadto
substantiallyimprovedperformanceonskeweddata,oftenu
singamuchsmallernumberof
components.Furthermore,variableselectioniseectivei
nremovingunnecessarycovariatesin
theskewness,whichmeansthatthereislittlelossinallowi
ngforskewnessinthecomponents
whenthedataareactuallysymmetric.Wealsointroducesmoo
thmixturesofgammaand
log-normalcomponentstomodelpositively-valuedrespons
evariables.
Keywords

In [52]:
pdfFileObj.close()

In [53]:
import docx

ModuleNotFoundError: No module named 'docx'

In [58]:
import requests
url = 'https://sp0.baidu.com/8aQDcjqpAAV3otqbppnN2DJv/api.php?resource_id=6899&query=失信执行人名单&iname=中国银行'
resp = requests.get(url)
import json
data = json.loads(resp.text, encoding='gb18030')
data.keys()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [56]:
import requests,json
url = 'http://m.ele.me/place/'
file = requests.get(url)
res = json.loads(file.text)
file1 = open('饭店.txt','a',encoding = 'utf-8')
for x in res:
    print(x['name'])
    file1.write(x['name']+'\n')
file1.close()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [59]:
import nltk

In [60]:
para = "Python is a widely used general-purpose, high-level programming language. Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than would be possible in languages such as C++ or Java."

In [61]:
from nltk.tokenize import sent_tokenize 

In [62]:
sent_tokenize(para)

['Python is a widely used general-purpose, high-level programming language.',
 'Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than would be possible in languages such as C++ or Java.']

In [63]:
from nltk.tokenize import word_tokenize
word_tokenize(para)

['Python',
 'is',
 'a',
 'widely',
 'used',
 'general-purpose',
 ',',
 'high-level',
 'programming',
 'language',
 '.',
 'Its',
 'design',
 'philosophy',
 'emphasizes',
 'code',
 'readability',
 ',',
 'and',
 'its',
 'syntax',
 'allows',
 'programmers',
 'to',
 'express',
 'concepts',
 'in',
 'fewer',
 'lines',
 'of',
 'code',
 'than',
 'would',
 'be',
 'possible',
 'in',
 'languages',
 'such',
 'as',
 'C++',
 'or',
 'Java',
 '.']

In [64]:
from nltk.corpus import stopwords

In [65]:
english_stops = set(stopwords.words('english'))
print(english_stops)

LookupError: 
**********************************************************************
  Resource 'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - 'C:\\Users\\147/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\147\\Anaconda3\\nltk_data'
    - 'C:\\Users\\147\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\147\\AppData\\Roaming\\nltk_data'
**********************************************************************

In [66]:
import sqlite3

In [73]:
connection = sqlite3.connect("survey.db")

In [74]:
cursor = connection.cursor()

In [75]:
cursor.execute("SELECT Site.lat, Site.long FROM Site;")

OperationalError: no such table: Site

In [76]:
results = cursor.fetchall()
for r in results:
    print(r)